server:
  port: 8080

spring:
  application:
    name: lamoda-monitor

  datasource:
    url: "jdbc:postgresql://localhost:5433/product"
    username: "postgres"
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: "smtp.gmail.com"
    port: "465"
    ssl:
      enable: "true"
    auth: "true"

monitor:
  base-url: "https://www.lamoda.ru/api/v1/product/get"

eamil:
  user-name-email: ${USER_NAME_EMAIL}
  user-password-email: ${USER_PASSWORD_EMAIL}







