spring:
  application:
    name: lamoda-monitor

  datasource:
    url: "jdbc:postgresql://localhost:5433/product"
    username: "postgres"
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: create